// automatically generated by the FlatBuffers compiler, do not modify

package sync

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type DstCSSyncInfo struct {
	_tab flatbuffers.Table
}

func GetRootAsDstCSSyncInfo(buf []byte, offset flatbuffers.UOffsetT) *DstCSSyncInfo {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &DstCSSyncInfo{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *DstCSSyncInfo) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *DstCSSyncInfo) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *DstCSSyncInfo) DstCSId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *DstCSSyncInfo) DstCSDir() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func DstCSSyncInfoStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func DstCSSyncInfoAddDstCSId(builder *flatbuffers.Builder, dstCSId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(dstCSId), 0)
}
func DstCSSyncInfoAddDstCSDir(builder *flatbuffers.Builder, dstCSDir flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(dstCSDir), 0)
}
func DstCSSyncInfoEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
