// automatically generated by the FlatBuffers compiler, do not modify

package sync

const (
	SpeedTypeSLOWEST = 1
	SpeedTypeFASTEST = 2
	SpeedTypeAVERAGE = 3
)

var EnumNamesSpeedType = map[int]string{
	SpeedTypeSLOWEST:"SLOWEST",
	SpeedTypeFASTEST:"FASTEST",
	SpeedTypeAVERAGE:"AVERAGE",
}

