// automatically generated by the FlatBuffers compiler, do not modify

package sync

const (
	TriggerTypeREGEX = 1
	TriggerTypeTIMER = 2
	TriggerTypeMANUAL = 3
	TriggerTypeREGEX_TIMER = 4
)

var EnumNamesTriggerType = map[int]string{
	TriggerTypeREGEX:"REGEX",
	TriggerTypeTIMER:"TIMER",
	TriggerTypeMANUAL:"MANUAL",
	TriggerTypeREGEX_TIMER:"REGEX_TIMER",
}

