// Code generated by "stringer -type=LogLevel"; DO NOT EDIT

package blog

import "fmt"

const _LogLevel_name = "CritWarnErrInfoDebug"

var _LogLevel_index = [...]uint8{0, 4, 8, 11, 15, 20}

func (i LogLevel) String() string {
	if i < 0 || i >= LogLevel(len(_LogLevel_index)-1) {
		return fmt.Sprintf("LogLevel(%d)", i)
	}
	return _LogLevel_name[_LogLevel_index[i]:_LogLevel_index[i+1]]
}
