// automatically generated by the FlatBuffers compiler, do not modify

package QfxCtrl

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CtrlLogin struct {
	_tab flatbuffers.Table
}

func GetRootAsCtrlLogin(buf []byte, offset flatbuffers.UOffsetT) *CtrlLogin {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CtrlLogin{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CtrlLogin) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CtrlLogin) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CtrlLogin) CtrlId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func (rcv *CtrlLogin) Ctrltype() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *CtrlLogin) MutateCtrltype(n int32) bool {
	return rcv._tab.MutateInt32Slot(6, n)
}

func CtrlLoginStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func CtrlLoginAddCtrlId(builder *flatbuffers.Builder, ctrlId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ctrlId), 0)
}
func CtrlLoginAddCtrltype(builder *flatbuffers.Builder, ctrltype int32) {
	builder.PrependInt32Slot(1, ctrltype, 0)
}
func CtrlLoginEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
