// automatically generated by the FlatBuffers compiler, do not modify

package QfxCtrl

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type CtrlLogout struct {
	_tab flatbuffers.Table
}

func GetRootAsCtrlLogout(buf []byte, offset flatbuffers.UOffsetT) *CtrlLogout {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &CtrlLogout{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *CtrlLogout) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *CtrlLogout) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *CtrlLogout) CtrlId() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func CtrlLogoutStart(builder *flatbuffers.Builder) {
	builder.StartObject(1)
}
func CtrlLogoutAddCtrlId(builder *flatbuffers.Builder, ctrlId flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(0, flatbuffers.UOffsetT(ctrlId), 0)
}
func CtrlLogoutEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
