// automatically generated by the FlatBuffers compiler, do not modify

package QfxCtrl

const (
	MsgTypeCPE_STATUS = 0
	MsgTypeCTRL_LOGIN = 1
	MsgTypeCTRL_LOGOUT = 2
	MsgTypeCTRL_MSG_ACK = 3
)

var EnumNamesMsgType = map[int]string{
	MsgTypeCPE_STATUS:"CPE_STATUS",
	MsgTypeCTRL_LOGIN:"CTRL_LOGIN",
	MsgTypeCTRL_LOGOUT:"CTRL_LOGOUT",
	MsgTypeCTRL_MSG_ACK:"CTRL_MSG_ACK",
}

