// automatically generated by the FlatBuffers compiler, do not modify

package QfxCtrl

const (
	QfxMsgNONE = 0
	QfxMsgCpeStatus = 1
	QfxMsgCtrlLogin = 2
	QfxMsgCtrlLogout = 3
	QfxMsgQfxMsgAck = 4
)

var EnumNamesQfxMsg = map[int]string{
	QfxMsgNONE:"NONE",
	QfxMsgCpeStatus:"CpeStatus",
	QfxMsgCtrlLogin:"CtrlLogin",
	QfxMsgCtrlLogout:"CtrlLogout",
	QfxMsgQfxMsgAck:"QfxMsgAck",
}

