// automatically generated by the FlatBuffers compiler, do not modify

package QfxCtrl

import (
	flatbuffers "github.com/google/flatbuffers/go"
)

type QfxMsgAck struct {
	_tab flatbuffers.Table
}

func GetRootAsQfxMsgAck(buf []byte, offset flatbuffers.UOffsetT) *QfxMsgAck {
	n := flatbuffers.GetUOffsetT(buf[offset:])
	x := &QfxMsgAck{}
	x.Init(buf, n+offset)
	return x
}

func (rcv *QfxMsgAck) Init(buf []byte, i flatbuffers.UOffsetT) {
	rcv._tab.Bytes = buf
	rcv._tab.Pos = i
}

func (rcv *QfxMsgAck) Table() flatbuffers.Table {
	return rcv._tab
}

func (rcv *QfxMsgAck) Msgid() int32 {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(4))
	if o != 0 {
		return rcv._tab.GetInt32(o + rcv._tab.Pos)
	}
	return 0
}

func (rcv *QfxMsgAck) MutateMsgid(n int32) bool {
	return rcv._tab.MutateInt32Slot(4, n)
}

func (rcv *QfxMsgAck) Dstid() []byte {
	o := flatbuffers.UOffsetT(rcv._tab.Offset(6))
	if o != 0 {
		return rcv._tab.ByteVector(o + rcv._tab.Pos)
	}
	return nil
}

func QfxMsgAckStart(builder *flatbuffers.Builder) {
	builder.StartObject(2)
}
func QfxMsgAckAddMsgid(builder *flatbuffers.Builder, msgid int32) {
	builder.PrependInt32Slot(0, msgid, 0)
}
func QfxMsgAckAddDstid(builder *flatbuffers.Builder, dstid flatbuffers.UOffsetT) {
	builder.PrependUOffsetTSlot(1, flatbuffers.UOffsetT(dstid), 0)
}
func QfxMsgAckEnd(builder *flatbuffers.Builder) flatbuffers.UOffsetT {
	return builder.EndObject()
}
